name: LocalXpose TCP Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and Install loclx
        run: |
          curl -L https://api.localxpose.io/api/downloads/loclx-linux-amd64.deb -o loclx.deb
          sudo dpkg -i loclx.deb
          sudo apt-get install -f -y

      - name: Start TCP Tunnel on port 80
        env:
          LX_TOKEN: bUKmQXQVc7rezi83ysAjeit9vx59WmAYaxuPhVvF
        run: |
          loclx tcp --port 80 --token $LX_TOKEN --keep-alive
