name: SSH via Serveo

on:
  workflow_dispatch:   # jalan manual

jobs:
  ssh-serveo:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Access
      run: |
        echo "=== Setup password untuk root ==="
        sudo apt-get update
        sudo apt-get install -y openssh-server
        echo "root:123456" | sudo chpasswd
        sudo service ssh start

        echo "=== Buat reverse tunnel ke Serveo ==="
        ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 serveo.net sleep 10h
