name: SSH via localhost.run (password)

on:
  workflow_dispatch: # manual trigger

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start
          echo "runner:runner" | sudo chpasswd

      - name: Start tunnel with localhost.run
        run: |
          ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 ssh.localhost.run
