name: Ubuntu SSH Runner via Cloudflare

on:
  workflow_dispatch:
  push:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
    - name: Update system & install SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server wget curl
        echo "root:github123" | sudo chpasswd
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo systemctl enable ssh
        sudo systemctl start ssh
        sudo systemctl status ssh --no-pager

    - name: Install Cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb
        sudo dpkg -i cloudflared.deb

    - name: Start Cloudflare Tunnel
      run: |
        # Gunakan tunnel ID langsung untuk menjalankan tunnel
        nohup cloudflared tunnel --url ssh://localhost:22 run _spectrum > cloudflared.log 2>&1 &
        sleep 10
        echo "Cloudflare Tunnel started."
        tail -n 20 cloudflared.log || true

    - name: Show SSH Info
      run: |
        echo "======================================="
        echo "SSH Server siap!"
        echo "Domain : bli4me.dpdns.org"
        echo "Login  : ssh root@bli4me.dpdns.org"
        echo "Password: github123"
        echo "Tunnel ID: 27305952-c5af-4d12-b089-e1e9d49bc659"
        echo "Tunnel Name: _spectrum"
        echo "======================================="
