name: SSH via Cloudflare Tunnel (TCP)

on:
  workflow_dispatch:   # bisa jalan manual
  push:                # atau otomatis tiap push

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          echo "root:12345" | sudo chpasswd
          sudo service ssh start

      - name: Install Cloudflare Tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflare Tunnel (TCP for SSH)
        run: |
          nohup cloudflared tunnel --url tcp://localhost:22 --protocol tcp --logfile tunnel.log > /dev/null 2>&1 &
          sleep 10
          cat tunnel.log | grep -E "trycloudflare.com"

      - name: Keep Alive
        run: sleep infinity
