name: SSH via Pinggy

on:
  workflow_dispatch:   # bisa dijalankan manual
  push:                # atau setiap push
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pinggy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -q https://github.com/pinggy-io/pinggy/releases/latest/download/pinggy_linux_amd64
          chmod +x pinggy_linux_amd64
          sudo mv pinggy_linux_amd64 /usr/local/bin/pinggy

      - name: Start SSH server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Start Pinggy Tunnel
        run: |
          # Expose port 22 via Pinggy
          nohup pinggy --ssh 22 > pinggy.log 2>&1 &
          sleep 10
          cat pinggy.log
