name: SSH Runner with Pinggy and Banner (Fixed)

on:
  workflow_dispatch:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update apt
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y openssh-server curl figlet

      - name: Setup SSH user
        run: |
          sudo useradd -m runner -s /bin/bash || true
          echo "runner:runner" | sudo chpasswd
          echo "runner ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/runner

      - name: Create SSH Banner File
        run: |
          echo "**********************************************" | sudo tee /etc/ssh/banner.txt
          echo "*                                            *" | sudo tee -a /etc/ssh/banner.txt
          echo "*      Welcome to GitHub Runner SSH!        *" | sudo tee -a /etc/ssh/banner.txt
          echo "*                                            *" | sudo tee -a /etc/ssh/banner.txt
          echo "*      Managed by Your Awesome Workflow     *" | sudo tee -a /etc/ssh/banner.txt
          echo "*                                            *" | sudo tee -a /etc/ssh/banner.txt
          echo "**********************************************" | sudo tee -a /etc/ssh/banner.txt

      - name: Enable SSH Banner
        run: |
          sudo sed -i '/^#Banner none/c\Banner /etc/ssh/banner.txt' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Start Pinggy TCP Tunnel
        run: |
          nohup ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 \
          -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 5
          cat pinggy.log

      - name: Keep workflow alive
        run: sleep infinity
