name: SSH via PageKite (Password)

on:
  workflow_dispatch:
  push:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Install PageKite & SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y pagekite openssh-server
        sudo service ssh start
        echo "root:github" | sudo chpasswd   # password root = github

    - name: Start PageKite Tunnel
      run: |
        nohup pagekite 22 undergraduate.pagekite.me:22 exk29b34eb4zbxfb8k8fz72xf4b4k88x > pk.log 2>&1 &
        sleep 5
        echo "✅ Tunnel started!"
        cat pk.log

    - name: Keep Alive
      run: |
        echo "🔑 Connect dengan perintah berikut:"
        echo "ssh root@undergraduate.pagekite.me -p 22"
        echo "Password: github"
        sleep 3600
