name: SSH via PageKite

on:
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Root Password
      run: |
        echo "root:github" | sudo chpasswd
        echo "✅ Password root diset ke 'github'"

    - name: Install PageKite
      run: |
        sudo apt-get update
        sudo apt-get install -y pagekite

    - name: Start PageKite SSH Tunnel
      run: |
        nohup pagekite ssh://localhost:22 undergraduate.pagekite.me:22 exk29b34eb4zbxfb8k8fz72xf4b4k88x > pk.log 2>&1 &
        sleep 8
        echo "✅ Tunnel started!"
        cat pk.log
