name: Ubuntu SSH via Pinggy

on:
  workflow_dispatch:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server

      - name: Setup SSH user
        run: |
          sudo useradd -m runner -s /bin/bash || true
          echo "runner:runner" | sudo chpasswd
          echo "runner ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/runner
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Start Pinggy tunnel
        run: |
          ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 \
          -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 5
          cat pinggy.log
